### ISSUE TITLE
[Bug] there are errors and also does not appear menu in mini-games (separate with customization of mini-games)

### ISSUE THREAD

**Issue by Cethra** [Lyzev/SchummelPartie#2]
### Describe the bug

![93](https://github.com/user-attachments/assets/b3e7f3bf-eba5-47ff-b1bb-c58b7b3dcca9)
There are errors that are on the screenshot when starting the game, as well as does not appear menu for customization in the mini-games themselves, before this all worked after the last update broke apparently (I have all updated urGUI also put)

### Steps to reproduce

```bash
install the new update pummel?
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
This should be fixed in latest version, if not let me know!
