### ISSUE TITLE
[Bug] The script does not work well in mini mode gift collection

### ISSUE THREAD

**Issue by Cethra** [Lyzev/SchummelPartie#3]
### Describe the bug

The script does not work well in mini mode gift collection

### Steps to reproduce

```bash
just playing..
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
The behavior is determined by an algorithm (bot), I won't be modifying the existing implementation. However, you're welcome to submit a pull request with improvements or a better approach. Contributions are always appreciated!
