### ISSUE TITLE
[Suggestion] Add trophies and Crowns

### ISSUE THREAD

**Issue by Yolomic** [Lyzev/SchummelPartie#4]
### Describe the feature

As the name suggests add the ability to add crowns or trophies or simply add all accessories

### Before submitting a suggestion

- [X] This feature doesn't already exist.
(I have checked the source on the **latest build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

**Comment by Lyzev** [comment]
This is already a feature in debug mode.
