### ISSUE TITLE
Can ESP be turned off?

### ISSUE THREAD

**Issue by linlin0060** [Lyzev/SchummelPartie#5]
### Describe the feature

As title

### Before submitting a suggestion

- [X] This feature doesn't already exist.
(I have checked the source on the **latest build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

**Comment by Lyzev** [comment]
As the README.md file says:
Graphical User Interface
Toggle the GUI with Insert or RightShift.

You can change and deactivate modifications in the interface.
